apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool
      ports:
        - containerPort: 8080
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      
