apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  restartPolicy: Never
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          ports:
          - containerPort: 8080
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 80

      
