apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: nginx
          containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
          containerPort: 8080
