apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: busybox 
          image: busybox:latest
          ports:
          - containerPort: 80
        - name: multitool
          image: multitool:latest
          ports:
          - containerPort: 8080



