
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 80
      initContainers:    
        - name: multitool
          image: wbitt/network-multitool
          ports:
          - containerPort: 8080
          command: ['sh', '-c', 'until nslookup my-app-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for my-app-service; sleep 2; done;']


