apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
          - containerPort: 80
      - image: wbitt/network-multitool
        name: multitool
        ports:
          - containerPort: 8080
        #  readinessProbe:
        #    httpGet:
         #     path: /
          #    port: 8080
          #  periodSeconds: 10
          #  timeoutSeconds: 5
