apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      initContainers:
      - name: multitool
        image: wbitt/network-multitool
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do echo $(date -u) >> /var/log/time.log; sleep 5; done;" ]


