apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
       containers:
         - name: nginx
           image: nginx:latest
           ports:
           - containerPort: 80
         - name: multitool
           image: wbitt/network-multitool
           command:
           - sleep
           - "3600"
       
