apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: myapp
  ports:
    - name: nginx
      port: 80
      targetPort: 9001
    - name: multitool
      port: 8080
      targetPort: 9002


